In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

filename = "./student_height_weight.txt"
df = pd.read_csv(filename, sep="\t", lineterminator="\r")

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ht      10 non-null     int64
 1   wt      10 non-null     int64
dtypes: int64(2)
memory usage: 292.0 bytes


In [3]:
df.head()

ht   wt
0  63  127
1  64  121
2  66  142
3  69  157
4  69  162

In [4]:
print(df.columns)

Index(['ht', 'wt'], dtype='object')


In [5]:
X = np.array(df["ht"]).reshape(-1, 1)
X

array([[63],
       [64],
       [66],
       [69],
       [69],
       [71],
       [71],
       [72],
       [73],
       [75]], dtype=int64)

In [6]:
y = np.array(df["wt"]).reshape(-1, 1)
y

array([[127],
       [121],
       [142],
       [157],
       [162],
       [156],
       [169],
       [165],
       [181],
       [208]], dtype=int64)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=42
)

In [8]:
lr_model = LinearRegression()

lr_model.fit(X_train, y_train)
print(lr_model.score(X_test, y_test))

0.8457440720378299


In [9]:
lr_model.predict([[63]])

array([[117.95070423]])

In [10]:
import pickle

pickle.dump(lr_model, open("model.pkl", "wb"))